workflows:
  ios-native-workflow:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: dousKey

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.dousspint.app

      vars:
        BUNDLE_ID: "com.dousspint.app"
        XCODE_PROJECT: "DousSpint.xcodeproj"
        XCODE_SCHEME: "DousSpint"
        APP_STORE_APPLE_ID: "6753706789"

      xcode: latest
      cocoapods: default

    scripts:
      - name: Set up provisioning profiles
        script: |
          echo "Setting up provisioning profiles..."
          xcode-project use-profiles

      - name: Increment build number
        script: |
          echo "Current working directory: $CM_WORKING_DIRECTORY"
          cd $CM_WORKING_DIRECTORY
          echo "Listing files in repository root:"
          ls -la
          echo "Running agvtool to check current version..."
          agvtool what-version
          echo "Fetching latest build number from App Store Connect..."
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          echo "Latest build number: $LATEST_BUILD_NUMBER"
          echo "Incrementing build number..."
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
          echo "Build number incremented successfully."

      - name: Build IPA for distribution
        script: |
          echo "Building IPA..."
          xcode-project build-ipa \
            --project "$CM_WORKING_DIRECTORY/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
          echo "IPA build finished."

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
